### ISSUE TITLE
Changing a provider's `runtimeConfigRef` doesn't create a new `ProviderRevision`

### ISSUE THREAD

**Issue by Kidswiss** [crossplane/crossplane#5068]
### What happened?
While debugging some issues, I found that changing a provider's `runtimeConfigRef` doesn't spawn a new `ProviderRevision`. This seems like a counterintuitive behavior to me.

While chatting with @phisco we both agreed that this would probably be considered a bug, or at least a sensible behavior.

### How can we reproduce it?
1. Apply a provider package
1. Wait for it to be ready
1. Change its `runtimeConfigRef`
1. No new `ProviderRevision` is created

### What environment did it happen in?
Crossplane version: 1.14.1

**Comment by Kidswiss** [comment]
Okay, if found a few more issues here.

Example:
* Migrating the providers from the controllerConfig to the runtimeConfig. 
* Remove the controllerConfigRef in the provider and the controllerConfig itself from the cluster.
* Add a runtimeConfig and add the ref to the provider.
* Apply everything.
* The provider gets unhealthy, because the currently active revision is neither updated with the new refs, nor replaced with another revision.
* Manual deletion of the revision is necessary.

**Comment by Kidswiss** [comment]
I just tried to reproduce it again with plain k8s. It still breaks, but differently. My other description was observed on OpenShift. On OpenShift no new revision was spawned for me, with the same events (cannot get referenced controller config). One other difference is that my first report is based on Crossplane 1.14.1 and this test on 1.14.3, so maybe some things were already fixed.

provider-controller-conf.yaml:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: "crossplanecontrib/provider-kubernetes:main"
  controllerConfigRef:
    name: kubernetes
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  labels:
    name: kubernetes
  name: kubernetes
spec:
  serviceAccountName: provider-kubernetes
```

provider-runtime-conf.yaml:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  labels:
    name: provider-kubernetes
  name: provider-kubernetes
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.9.0
  runtimeConfigRef:
    name: provider-kubernetes
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              securityContext: {}
          securityContext: {}
          serviceAccountName: provider-kubernetes
```

```
kubectl apply -f provider-controller-conf.yaml
# wait until its ready

kubectl delete controllerconfigs.pkg.crossplane.io kubernetes
kubectl apply -f provider-runtime-conf.yaml 
```

Inspect the revisions, first the old one:
```
  Warning  SyncPackage        10s (x16 over 6m39s)   packages/providerrevision.pkg.crossplane.io  cannot prepare runtime manifest builder options: cannot get referenced controller config: ControllerConfig.pkg.crossplane.io "kubernetes" not found
```

And the new one:
```
  Warning  SyncPackage      54s (x11 over 6m53s)   packages/providerrevision.pkg.crossplane.io  cannot establish control of object: providerconfigusages.kubernetes.crossplane.io is already controlled by ProviderRevision provider-kubernetes-25f96d7ba8c1 (UID 4b84daf4-6ff5-4f6b-a9f4-8f0c522b48bf)
```

**Comment by zonybob** [comment]
Just wanted to chime in that I also experience this issue... Crossplane 1.14.5... on OpenShift (K8s 1.27)

* The `controllerConfigRef` is patched out of the `Provider`
* The `runtimeConfigRef` is patched into the `Provider`
* No new `ProviderRevision` is created
* The most recent `ProviderRevision` gets updated with the `runtimeConfigRef` but it also hangs on to the `controllerConfigRef`
* The error is as below...

```
cannot prepare runtime manifest builder options: cannot get referenced controller config: ControllerConfig.pkg.crossplane.io "crossplane-openshift-config" not found
```

**Comment by blakeromano** [comment]
Ran into this issue too.

To fix it temporarily you can do this 
```bash
#!/bin/bash

# Get a list of all ProviderRevision resources
resources=$(kubectl get providerrevisions -o custom-columns=NAME:.metadata.name --no-headers)

# Iterate through each resource and update the CRD
for resource in $resources; do
  echo "Updating ProviderRevision: $resource"

  # Use kubectl patch to remove spec.controllerConfigRef field
  kubectl patch providerrevisions $resource --type='json' -p='[
    {"op": "remove", "path": "/spec/controllerConfigRef"},
    {"op": "add", "path": "/spec/runtimeConfigRef/name", "value": "DEPLOYMENT_RUNTIME_NAME"}
  ]'
done

echo "Update complete for all ProviderRevisions"
```

**Comment by jbw976** [comment]
Thanks for all the information here folks, and thank you for the workaround @blakeromano!

We're tracking this issue in https://github.com/crossplane/crossplane/issues/5320 so it should be addressed before `DeploymentRuntimeConfig` is moved to GA ✅

**Comment by RonaldLePape** [comment]
This old problem is still there (checked today with v2.3.1), and linked to Roadmap Priority #5320 .

My proposal would be addressing the bug in a minimal & simple way that would still resolve the "trailing controllerConfigRef" problem.

Today we have this:
```
revisionName := xpkg.FriendlyID(p.GetName(), pkg.DigestHex())
``` 

# Proposal: 

I suggest this:
```
revisionID := pkg.DigestHex()

if ref := p.GetRuntimeConfigRef(); ref != nil {
    revisionID = hash(revisionID, ref.APIVersion, ref.Kind, ref.Name)
}

revisionName := xpkg.FriendlyID(p.GetName(), revisionID)
```

This is minimal because runtimeConfig content is not taken into account, only runtilmeConfigRef field value in provider object.

The old revision doesn't seem to be copied because a fresh revision is created:
```
pr := r.newPackageRevision()
```

**Comment by phisco** [comment]
@RonaldLePape, sounds reasonable to me. Are you interested in opening a PR?

**Comment by RonaldLePape** [comment]
yes, I'll give it a try

**Comment by RonaldLePape** [comment]
PR #7473 submitted.

**Comment by RonaldLePape** [comment]
As a side effect to changing package revision name function (feeding runtimeConfigRef value in the hash function), some e2e tests are now failing due to yaml-hardcoded values which are no longer correct. I'm trying to rewrite impacted tests so that they no longer need yaml files to fectch expected values.

So far the impacted tests corrected are: 
`TestCommonAnnotationsAndLabels`
`TestUpgradeDependencyDigest`

**Comment by RonaldLePape** [comment]
All CI tests passed, PR test error because i did not tick backport support

**Comment by RonaldLePape** [comment]
Feature gate added for `EnableBetaDeploymentRuntimeConfigs`

**Comment by RonaldLePape** [comment]
Failure CI : first 2 attempts dont look linked to code and third one is unclear. Can CI checks be re-run ?

These 2 tests are ok in my homelab:

`./nix.sh run .#e2e --  --test-suite base -labels area=pkg`
and
`./nix.sh run .#e2e --   --test-suite package-dependency-updates   -labels area=pkg`

**Comment by RonaldLePape** [comment]
CI test all clear this time. Do I have something to do regardin PR test ("checklist-completed") ?

**Comment by phisco** [comment]
> CI test all clear this time. Do I have something to do regardin PR test ("checklist-completed") ?

Nono, nothing to do. If you want you can strike through the missing backport line, but it's not a required check. I'll have a more thorough look at the pr today.

**Comment by RonaldLePape** [comment]
@phisco : Hi, do you have the possibility to re-run my PR CI checks ? (No bother if you cant ! )
